#!/usr/bin/env python

import rospy
from math import *
from nav_msgs.msg import *
from visualization_msgs.msg import *

def path_cb(path):
    rospy.loginfo('received a path')
    m = Marker()
    m.header = path.header
    m.pose.orientation.w = 1.0
    m.ns = "path_marker"
    m.id = 0
    m.type = Marker.LINE_STRIP
    m.scale.x = 0.04
    m.color.r = r
    m.color.g = g
    m.color.b = b
    m.color.a = 1.0
    for pose_stamped in path.poses:
        m.points.append(pose_stamped.pose.position)
    marker_pub.publish(m)

if __name__=="__main__":
    rospy.init_node("path_marker")
    path_topic_name = rospy.get_param('~path_topic_name', '/interpolated_path')
    rospy.Subscriber(path_topic_name, Path, path_cb)
    marker_topic_name = rospy.get_param('~marker_topic_name', '/interpolated_path_marker')
    marker_pub = rospy.Publisher(marker_topic_name, Marker,queue_size=10)
    r  = rospy.get_param('~color_r', 0)
    g  = rospy.get_param('~color_g', 1)
    b  = rospy.get_param('~color_b', 0)

    rospy.spin()

